// flow-typed signature: 416020bf851d5f029d6a4285f899cbf0
// flow-typed version: <<STUB>>/eslint-config-rallycoding_v^3.2.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-rallycoding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-rallycoding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-rallycoding/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-rallycoding/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-rallycoding/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-rallycoding/rules/imports' {
  declare module.exports: any;
}

declare module 'eslint-config-rallycoding/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-rallycoding/rules/react-a11y' {
  declare module.exports: any;
}

declare module 'eslint-config-rallycoding/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-rallycoding/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-rallycoding/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-rallycoding/rules/variables' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-rallycoding/index' {
  declare module.exports: $Exports<'eslint-config-rallycoding'>;
}
declare module 'eslint-config-rallycoding/index.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding'>;
}
declare module 'eslint-config-rallycoding/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/best-practices'>;
}
declare module 'eslint-config-rallycoding/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/errors'>;
}
declare module 'eslint-config-rallycoding/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/es6'>;
}
declare module 'eslint-config-rallycoding/rules/imports.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/imports'>;
}
declare module 'eslint-config-rallycoding/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/node'>;
}
declare module 'eslint-config-rallycoding/rules/react-a11y.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/react-a11y'>;
}
declare module 'eslint-config-rallycoding/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/react'>;
}
declare module 'eslint-config-rallycoding/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/strict'>;
}
declare module 'eslint-config-rallycoding/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/style'>;
}
declare module 'eslint-config-rallycoding/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-rallycoding/rules/variables'>;
}
